Refactor everything

diff --git a/lvm b/lvm
--- a/lvm
+++ b/lvm
@@ -2,6 +2,7 @@
 
 # Copyright 2015 The Kubernetes Authors.
 # Copyright 2017 Piotr Mazurkiewicz <piotr.mazurkiewicz@sysoperator.pl>
+# Copyright 2019 Niels Boehm <blubberdiblub@gmail.com>
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -15,173 +16,224 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# Required packages:
-#
-#  - jq
-#  - thin-provisionig-tools
-#
-usage() {
-	cat <<EOF
-Invalid usage. Usage:
-  $0 init
-  $0 attach <json params> <nodename>
-  $0 detach <mount device> <nodename>
-  $0 waitforattach <mount device> <json params>
-  $0 mountdevice <mount dir> <mount device> <json params>
-  $0 unmountdevice <mount dir>
-  $0 isattached <json params> <nodename>
-EOF
-	exit 1
+# lvm pesters us with warnings that throw flexVolume off track, so suppress them
+export LVM_SUPPRESS_FD_WARNINGS=1
+
+fail_hard() {
+  echo "$*" >&2
+  exit 2
 }
 
-ismounted() {
-	MOUNT=$(findmnt -n "${MNTPATH}" 2>/dev/null | cut -d' ' -f1)
-	[ "${MOUNT}" = "${MNTPATH}" ]
+for cmd in blkid jq lvcreate mkfs mount mountpoint umount ; do
+  command -v "$cmd" > /dev/null || fail_hard "missing command $cmd"
+done
+
+json_add_simple() {
+  [ $# -eq 2 ] || fail_hard "json_add_simple(): takes exactly 2 arguments"
+
+  jq -c --arg key "$1" --arg value "$2" '. + {($key): $value}' || fail_hard "json_add_simple(): jq failed"
 }
 
-getdevice() {
-	VOLUMEID=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.volumeID')
-	VG=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.volumegroup')
+json_add_json() {
+  [ $# -eq 2 ] || fail_hard "json_add_json(): takes exactly 2 arguments"
 
-	# LVM substitutes - with --
-	VOLUMEID=$(printf -- '%s' "$VOLUMEID" | sed s/-/--/g)
-	VG=$(printf -- '%s' "$VG" | sed s/-/--/g)
+  jq -c --arg key "$1" --argjson value "$2" '. + {($key): $value}' || fail_hard "json_add_json(): jq failed"
+}
 
-	DMDEV="/dev/mapper/${VG}-${VOLUMEID}"
-	printf -- '%s' "$DMDEV"
+json_get() {
+  [ $# -eq 2 ] || fail_hard "json_get(): takes exactly 2 arguments"
+
+  jq -n -e -r --argjson parse "$1" --arg key "$2" '$parse[$key]' || fail_hard "json_get(): jq failed"
+}
+
+json_get_string() {
+  [ $# -eq 2 ] || fail_hard "json_get_string(): takes exactly 2 arguments"
+
+  jq -n -r --argjson parse "$1" --arg key "$2" '$parse[$key] | select(type=="string")' || fail_hard "json_get_string(): jq failed"
+}
+
+reply_status() {
+  [ $# -eq 1 ] || fail_hard "reply_status(): takes exactly 1 argument"
+
+  printf '{}' | json_add_simple status "$1" || fail_hard "reply_status(): building reply failed"
+}
+
+reply_simple() {
+  [ $# -eq 3 ] || fail_hard "reply_simple(): takes exactly 3 arguments"
+
+  reply_status "$1" | json_add_simple "$2" "$3" || fail_hard "reply_simple(): building reply failed"
+}
+
+reply_json() {
+  [ $# -eq 3 ] || fail_hard "reply_json(): takes exactly 3 arguments"
+
+  reply_status "$1" | json_add_json "$2" "$3" || fail_hard "reply_json(): building reply failed"
+}
+
+lv_report() {
+  [ $# -eq 1 ] || fail_hard "lv_report(): takes exactly 1 argument"
+
+  lv_report=$( lvs --select "$1" -o lv_all --reportformat json ) || fail_hard "lv_report(): lvs failed"
+  [ "$( jq -n --argjson parse "$lv_report" '$parse["report"] | length == 1' )" = "true" ] || fail_hard "lv_report(): report ill-structured"
+  lvs_matched=$( jq -n --argjson parse "$lv_report" '$parse["report"][]["lv"] | length' ) || fail_hard "lv_report(): report ill-structured"
+  [ "$lvs_matched" -le 1 ] || fail_hard "lv_report(): selection too broad"
+
+  [ "$lvs_matched" -eq 1 ] || return 1
+  jq -n -c --argjson parse "$lv_report" '$parse["report"][]["lv"][]' || fail_hard "lv_report(): jq failed"
+}
+
+init() {
+  [ $# -eq 0 ] || fail_hard "init(): takes no arguments"
+
+  reply_json Success capabilities "$( printf '{}' | json_add_json attach true )" || fail_hard "init(): building reply failed"
 }
 
 attach() {
-	JSON_PARAMS=$1
-	VOLUMEID=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.volumeID')
-	VG=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.volumegroup')
-	THINPOOL=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.thinpool | select(type == "string")')
-	SIZE=$(printf -- '%s' "${JSON_PARAMS}" | jq -r '.size')
+  [ $# -eq  2 ] || fail_hard "attach(): takes exactly 2 arguments"
 
-	DMDEV=$(getdevice)
-	if [ ! -b "${DMDEV}" ]; then
-		if [ -n "${THINPOOL}" ]; then
-			lvcreate -n "$VOLUMEID" -V "$SIZE" --thinpool "$VG/$THINPOOL" > /dev/null && created=true || created=false
-		else
-			lvcreate -n "$VOLUMEID" -L "$SIZE" "$VG" > /dev/null && created=true || created=false
-		fi
+  volumegroup=$( json_get "$1" volumegroup )
+  thinpool=$( json_get_string "$1" thinpool )
+  volumeID=$( json_get "$1" volumeID )
+  size=$( json_get "$1" size )
 
-		if ! $created; then
-			jq -n --arg vol "$VG/$VOLUMEID" '{"status": "Failure", "message": ("Could not attach " + $vol)}'
-			exit 1
-		fi
-	fi
+  if lv_report=$( lv_report 'lv_full_name="'"$volumegroup/$volumeID"'"' ) ; then
+    lv_dm_path=$( json_get "$lv_report" lv_dm_path )
+    reply_simple Success device "$lv_dm_path"
+    return 0
+  fi
 
-	jq -n --arg dev "$DMDEV" '{"status": "Success", "device": $dev}'
-	exit 0
-}
+  if [ -z "$thinpool" ] ; then
+    lvcreate --name "$volumeID" --size "$size" -- "$volumegroup" > /dev/null 2>&1 && success=true || success=false
+  else
+    lvcreate --name "$volumeID" --virtualsize "$size" --thinpool "$thinpool" -- "$volumegroup" > /dev/null 2>&1 && success=true || success=false
+  fi
 
-detach() {
-	jq -n '{"status": "Success"}'
-	exit 0
+  if ! $success ; then
+    reply_simple Failure message "Could not attach $volumegroup/$volumeID"
+    exit 1
+  fi
+
+  if ! lv_report=$( lv_report 'lv_full_name="'"$volumegroup/$volumeID"'"' ) ; then
+    reply_simple Failure message "Could not query $volumegroup/$volumeID"
+    exit 1
+  fi
+
+  lv_dm_path=$( json_get "$lv_report" lv_dm_path )
+  reply_simple Success device "$lv_dm_path"
 }
 
 waitforattach() {
-	shift
-	attach "$@"
-}
+  [ $# -eq  2 ] || fail_hard "waitforattach(): takes exactly 2 arguments"
 
-domountdevice() {
-	MNTPATH=$1
-	DMDEV=$2
-	FSTYPE=$(printf -- '%s' "$3" | jq -r '.["kubernetes.io/fsType"]')
-	MNTOPTIONS=$(printf -- '%s' "$3" | jq -r '.mountoptions | select(type == "string")')
+  lv_dm_path="$1"
+  if [ -z "$lv_dm_path" ] ; then
+    intercept=$( attach "$2" "" ) || exit 1
+    lv_dm_path=$( json_get "$intercept" device )
+  fi
 
-	if [ ! -b "${DMDEV}" ]; then
-		jq -n --arg dev "$DMDEV" '{"status": "Failure", "message": ($dev + " does not exist")}'
-		exit 1
-	fi
+  if ! lv_report=$( lv_report 'lv_dm_path="'"$lv_dm_path"'"' ) ; then
+    reply_simple Failure message "Could not find volume $lv_dm_path"
+    exit 1
+  fi
 
-	if ismounted ; then
-		jq -n '{"status": "Success"}'
-		exit 0
-	fi
+  if [ -z "$( json_get_string "$lv_report" lv_active_locally )" ] ; then
+    reply_simple Failure message "Volume $lv_dm_path not active locally"
+    exit 1
+  fi
 
-	VOLFSTYPE=$(blkid -o udev "${DMDEV}" 2>/dev/null|grep "ID_FS_TYPE"|cut -d"=" -f2)
-	if [ "${VOLFSTYPE}" = "" ]; then
-		if ! mkfs -t "${FSTYPE}" "${DMDEV}" >/dev/null 2>&1 ; then
-			jq -n --arg fs "$FSTYPE" --arg dev "$DMDEV" '{"status": "Failure", "message": ("Failed to create fs " + $fs + " on device " + $dev)}'
-			exit 1
-		fi
-	fi
+  if [ -z "$( blkid -s TYPE -o value -d -- "$lv_dm_path" )" ] ; then
+    fstype=$( json_get_string "$2" kubernetes.io/fsType )
+    if ! mkfs -t "${fstype:-ext4}" -- "$lv_dm_path" > /dev/null 2>&1 ; then
+      reply_simple Failure message "Failed to create fs $fstype on device $lv_dm_path"
+      exit 1
+    fi
+  fi
 
-	mkdir -p "${MNTPATH}" > /dev/null 2>&1
-
-	if ! mount ${MNTOPTIONS:+-o "$MNTOPTIONS"} "${DMDEV}" "${MNTPATH}" > /dev/null 2>&1 ; then
-		jq -n --arg dev "$DMDEV" --arg mnt "$MNTPATH" '{"status": "Failure", "message": ("Failed to mount device " + $dev + " at " + $mnt)}'
-		exit 1
-	fi
-
-	jq -n '{"status": "Success"}'
-	exit 0
-}
-
-unmountdevice() {
-	MNTPATH=$1
-	if [ ! -d "${MNTPATH}" ]; then
-		jq -n '{"status": "Success"}'
-		exit 0
-	fi
-
-	if ! ismounted ; then
-		jq -n '{"status": "Success"}'
-		exit 0
-	fi
-
-	if ! umount "${MNTPATH}" > /dev/null 2>&1 ; then
-		jq -n --arg mnt "$MNTPATH" '{"status": "Failed", "message": ("Failed to unmount volume at " + $mnt)}'
-		exit 1
-	fi
-
-	jq -n '{"status": "Success"}'
-	exit 0
+  reply_simple Success device "$lv_dm_path"
 }
 
 isattached() {
-	jq -n '{"status": "Success", "attached": true}'
-	exit 0
+  [ $# -eq  2 ] || fail_hard "isattached(): takes exactly 2 arguments"
+
+  volumegroup=$( json_get "$1" volumegroup )
+  volumeID=$( json_get "$1" volumeID )
+
+  if ! lv_report=$( lv_report 'lv_full_name="'"$volumegroup/$volumeID"'"' ) ; then
+    reply_json Success attached false
+    return 0
+  fi
+
+  if [ -z "$( json_get_string "$lv_report" lv_active )" ] ; then
+    reply_json Success attached false
+    return 0
+  fi
+
+  reply_json Success attached true
 }
 
+detach() {
+  reply_status Success
+}
+
+mountdevice() {
+  [ $# -eq  3 ] || fail_hard "mountdevice(): takes exactly 3 arguments"
+
+  if ! lv_report=$( lv_report 'lv_dm_path="'"$2"'"' ) ; then
+    reply_simple Failure message "Could not find volume $2"
+    exit 1
+  fi
+
+  if mountpoint -q -- "$1" ; then
+    reply_status Success
+    return 0
+  fi
+
+  if ! mkdir -p -- "$1" > /dev/null 2>&1 ; then
+    reply_simple Failure message "Failed to make directory $1"
+    exit 1
+  fi
+
+  fstype=$( json_get_string "$3" kubernetes.io/fsType )
+  mountoptions=$( json_get_string "$3" mountoptions )
+
+  if ! mount ${fstype:+-t "$fstype"} ${mountoptions:+-o "$mountoptions"} -- "$2" "$1" > /dev/null 2>&1 ; then
+    reply_simple Failure message "Failed to mount device $2 at $1"
+    exit 1
+  fi
+
+  reply_status Success
+}
+
+unmountdevice() {
+  [ $# -eq  1 ] || fail_hard "mountdevice(): takes exactly 1 argument"
+
+  if ! mountpoint -q -- "$1" ; then
+    reply_status Success
+    return 0
+  fi
+
+  if ! umount -- "$1" > /dev/null 2>&1 ; then
+    reply_simple Failure message "Failed to unmount volume at $1"
+    exit 1
+  fi
+
+  reply_status Success
+}
+
+[ $# -ge 1 ] || fail_hard "missing operation"
+
 op=$1
-
-if [ "$op" = "init" ]; then
-	jq -n '{"status": "Success"}'
-	exit 0
-fi
-
-if [ $# -lt 2 ]; then
-	usage
-fi
-
 shift
 
 case "$op" in
-	attach)
-		attach "$@"
-		;;
-	detach)
-		detach "$@"
-		;;
-	waitforattach)
-		waitforattach "$@"
-		;;
-	mountdevice)
-		domountdevice "$@"
-		;;
-	unmountdevice)
-		unmountdevice "$@"
-		;;
-	isattached)
-                isattached "$@"
-                ;;
-	*)
-		jq -n '{"status": "Not supported"}'
-		exit 0
+init)          init "$@"          ;;
+attach)        attach "$@"        ;;
+waitforattach) waitforattach "$@" ;;
+isattached)    isattached "$@"    ;;
+detach)        detach "$@"        ;;
+mountdevice)   mountdevice "$@"   ;;
+unmountdevice) unmountdevice "$@" ;;
+*)
+  reply_status "Not supported"
+  exit 1
 esac
-
-exit 1
